ci_service: travis_ci
coverage_service: coveralls
xcodeproj: MyDictionary_App_Swift.xcodeproj
workspace: MyDictionary_App_Swift.xcworkspace
scheme: MyDictionary_App_Swift
source_directory: MyDictionary_App_Swift
ignore:
  - "../**/*/Xcode*"
