language: swift
osx_image: xcode12.5.1
script:
  - xcodebuild -scheme MyDictionary_App_Swift -workspace MyDictionary_App_Swift.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)

