name: Build

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependences
      run: |
        pod repo update
        pod install
    - name: Build
      run: xcodebuild -workspace MyDictionary_App_Swift.xcworkspace -scheme MyDictionary_App_Swift
