# Installs pod dependencies and then runs the unit test suite
name: CI

# Trigger CI when pushing to main, or opening PRs to main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    # Run on latest supported macOS version
    runs-on: macos-latest

    steps:
    
    # Check-out the repo
    - name: Check out Repository
      uses: actions/checkout@v2
      
    # Install the bundle dependencies
    - name: Install dependencies
      run: bundle install && bundle exec pod install
      
    # Run Unit Tests
    - name: Run Unit Tests
      run: bundle exec fastlane test
