name: MyDictionary CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  
  iOS:
    name: Unit Test iOS
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app
      WORKSPACE_NAME: MyDictionary_App_Swift.xcworkspace
      SCHEME_NAME: MyDictionary_App_Swift
    strategy:
      matrix:
        destination: ["name=iPhone 12 Pro"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache RubyGems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - name: Install ruby gems.
        run: bundle install
        
      - name: Install pods.
        run: pod install

      - name: iOS - ${{ matrix.destination }}
        run: |
          set -o pipefail
          xcodebuild build build-for-testing -workspace "${{ env.WORKSPACE_NAME }}" -scheme "${{ env.SCHEME_NAME }}" -destination "${{ matrix.destination }}" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | bundle exec xcpretty -c
