name: Testing

on: [push]

jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-11
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: CocoaPods Install
        run: pod install
        
      - name: Testing iOS app
        run: exec sh ./.github/scripts/test_app.sh

